FROM openjdk:11-jdk-slim
ENV PORT 8080
EXPOSE 8080

COPY *.jar app.jar
CMD ["java", "-XX:+UseG1GC", "-XX:MaxMetaspaceSize=512m", "-XX:MetaspaceSize=256m", "-Dspring.profiles.active=dev", "-jar", "app.jar"]