spring:
  profiles:
    active: local

app:
  artifactId: @project.artifactId@

server:
  port: 8080

---
spring:
  profiles: local
  http:
    encoding:
      force: true
  devtools:
    livereload:
      enabled: true
      port: 35730
    restart:
      enabled: true
  thymeleaf:
    cache: false
  resources:
    static-locations:
      - classpath:/static/
      - https://s3.ap-northeast-2.amazonaws.com/local.static.myrecipes.link/static/
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.springframework.web: TRACE

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: local.static.myrecipes.link

app:
  image-path:
    recipe: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/recipe/
    step: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/step/
  api:
    recipe:
      scheme: http
      host: localhost
      port: 8081
    member:
      scheme: http
      host: localhost
      port: 8081
  index:
    page-size: 9
    sort-field: registerDate
    is-descending: true
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail

---
spring:
  profiles: dev
  http:
    encoding:
      force: true
  thymeleaf:
    cache: false
  resources:
    static-locations:
      - classpath:/static/
      - https://s3.ap-northeast-2.amazonaws.com/dev.static.myrecipes.link/static/
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: 10.0.10.206
    port: 6379
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.springframework.web: TRACE

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: dev.static.myrecipes.link

app:
  image-path:
    recipe: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/recipe/
    step: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/step/
  api:
    recipe:
      scheme: http
      host: 10.0.20.156
      port: 8081
    member:
      scheme: http
      host: 10.0.20.156
      port: 8081
  index:
    page-size: 9
    sort-field: registerDate
    is-descending: true
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail

---
spring:
  profiles: prod
  http:
    encoding:
      force: true
  thymeleaf:
    cache: true
  resources:
    static-locations:
      - classpath:/static/
      - https://s3.ap-northeast-2.amazonaws.com/static.myrecipes.link/static/
  cache:
    type: redis
    redis:
      time-to-live: 10000
  redis:
    host: 10.0.10.206
    port: 6379
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.springframework.web: TRACE

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: static.myrecipes.link

app:
  image-path:
    recipe: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/recipe/
    step: https://s3.ap-northeast-2.amazonaws.com/${cloud.aws.s3.bucket}/step/
  api:
    recipe:
      scheme: http
      host: service.myrecipes.link
      port: 8081
    member:
      scheme: http
      host: service.myrecipes.link
      port: 8081
  index:
    page-size: 9
    sort-field: registerDate
    is-descending: true
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail
